### PR TITLE
Update GeneralInfo.php

### PR DESCRIPTION
**Pull request by simonsolutions**
Extend API Response fields

### CODE REVIEW

**Comment by sibprogrammer** [comment]
The corresponding functional test (SiteTest.php) should be adjusted.

**Comment by simonsolutions** [comment]
The SiteTest has so far no checks for the Test-sites, so in which method you do a change?

**Review by sibprogrammer — COMMENTED** [review]
> The SiteTest has so far no checks for the Test-sites, so in which method you do a change?

"testGet" method I think

**Comment by sibprogrammer** [comment]
Merged. See 9d36db668bbc9074e71d35668f9930ec3179f825

**Pull request closed without merging**
