### PR TITLE
Update SessionTest.php

### PR DESCRIPTION
**Pull request by simonsolutions**
Add Test for new Session Create Method

### CODE REVIEW

**Comment by sibprogrammer** [comment]
It should be a part of pull request #106 to keep it atomic.

**Comment by sibprogrammer** [comment]
StyleCI violations

**Comment by simonsolutions** [comment]
Github doesn't let me merge the two request nor let me add another file to the request

**Comment by sibprogrammer** [comment]
Merged in scope of f881d91f831d93fd1a61fff174d6ec40214c71af

**Pull request closed without merging**
